# SITE CONFIGURATION
title: Kriti Sahu # your site title
author: ninjakx # You :P
description: > # Meta description of Homepage
 My personal blog website with portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ninjakx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Kriti Sahu
  links:
    - https://www.linkedin.com/in/kriti-sahu-386486163
    - https://github.com/ninjakx

  

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/', sym: 'home'}
  - {name: 'About', link: '/about', sym: 'user'}
  - {name: 'Contact', link: '/contact', sym: 'pencil-square-o'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/bg.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: kritisahu26@gmail.com # email for form submission

stackoverflow_username: pygirl # replace with your_twitter_username or comment to remove link from footer
github_username:  ninjakx # replace with your_github_username or comment to remove link from footer
linkedin_username: None

disqus:
  shortname: ninjakx # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
